# frontend-deployment.yaml
# VERSIÓN CORREGIDA: Configuración de Nginx robusta para Single Page Applications (SPA)

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;

      # La raíz donde se encuentran los archivos de Angular (index.html, etc.)
      root /usr/share/nginx/html;
      
      # --- BLOQUE MEJORADO Y CORREGIDO ---
      # Esta sección maneja las peticiones a la API y las redirige al backend.
      # Es importante que vaya antes del bloque genérico para que sea procesada primero.
      location /api/ {
        proxy_pass http://backend-service:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      # Esta es la directiva clave para las Single Page Applications como Angular.
      # Para cualquier otra ruta que no sea la API, se debe servir el archivo index.html
      # para que el router de Angular pueda manejar la ruta internamente en el navegador.
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
---
# Deployment para el Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: kennysolo/invopay-frontend:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: frontend-nginx-conf
---
# Service para el Frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 8081

