# k8s/secrets.template.yaml
# INSTRUCCIONES: Copia este archivo a 'secrets.yaml' (que está en .gitignore).
# Reemplaza los valores de ejemplo con los valores reales codificados en Base64.
# Para codificar: echo -n 'tu-valor-secreto' | base64
# Para archivos: cat /ruta/al/archivo.json | base64

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  # --- Reemplaza estos valores ---
  DB_URL: amRiYzp...
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET_KEY: ZHNmc2...
  SECURE_SECRET_KEY: ZHNmc2...
  MAIL_HOST: c210c...
  MAIL_PORT: NTg3
  MAIL_USERNAME: dXNlckBleGFtcGxlLmNvbQ==
  MAIL_PASSWORD: cGFzc3dvcmQ=
  BUCKET_ID: dGVja...
  PROJECT_ID: dGVja...
  BUCKET_NAME: dGVja...
  ALLOWED_ORIGINS: Imh0dHA6Ly9leGFtcGxlLmNvbSI=
  JWT_EXPIRATION: Mjg4MDAwMDA=
  JWT_REFRESH_TOKEN_EXPIRATION: NjA0ODAwMDAw
---
apiVersion: v1
kind: Secret
metadata:
  name: google-credentials
type: Opaque
data:
  # --- Reemplaza este valor con tu archivo de credenciales en base64 ---
  techforb-finsuite-key.json: ewoiandr...
